Wg/fix schema description default (#53624)
Drift from the addition of a default value to a table schema provides an
invalid sql query to fix

![Screenshot 2023-06-16 at 1 53 19
PM](https://github.com/sourcegraph/sourcegraph/assets/13024338/1a74c19c-b25e-4310-b126-65bc1e4fb3bb)

```sql
sourcegraph=# ALTER TABLE notebooks ALTER COLUMN public SET DEFAULT ;
ERROR:  syntax error at or near ";"
LINE 1: ALTER TABLE notebooks ALTER COLUMN public SET DEFAULT ;
                                                              ^
```

## Test plan

Tested locally against the example above and against a more complex
case.

Introducing the following drift:
```
ALTER TABLE users 
ALTER COLUMN created_at 
SET DEFAULT '2020-01-01 00:00:00';
```

Case DEFAULT should be null:
![Screenshot 2023-06-16 at 2 12 14
PM](https://github.com/sourcegraph/sourcegraph/assets/13024338/05d582b4-173c-4ed2-a51f-ba18bc461d4b)

Case DEFAULT should have a different value:
![Screenshot 2023-06-16 at 2 16 52
PM](https://github.com/sourcegraph/sourcegraph/assets/13024338/bdb28691-35cc-43b3-b92e-2edfdc52ded5)



<!-- All pull requests REQUIRE a test plan:
https://docs.sourcegraph.com/dev/background-information/testing_principles
-->

---------

Co-authored-by: Eric Fritz <eric@sourcegraph.com>