completions/http: fix broken stream error reporting (#53510)
In https://github.com/sourcegraph/sourcegraph/pull/52791 I added a
`WriteHeader` in an attempt to propagate HTTP status codes from upstream
back to clients. It turns out this is illegal when using the headers set
by `streamhttp.Writer`, and was silently breaking error results, which
causes [the issue I noticed where no errors is reported in Cody
UIs](https://github.com/sourcegraph/sourcegraph/issues/53177#issuecomment-1588063069).
The errors are as follows, the first internal to `net/http`, and the
second from a newly added error log:

```
2023/06/14 19:32:59 http: WriteHeader called with both Transfer-Encoding of "chunked" and a Content-Length of 90
ERROR completions.chat httpapi/stream.go:55 error reporting streaming completion error {"trace.family": "session > completions.chat", "error": "http: wrote more than the declared Content-Length"}
```

Removing the header writing makes things work again as before. There
might be a more appropriate way to propagate status codes but I think it
best that we just revert the header write for now. I added some
docstrings to document what I noticed.

Closes https://github.com/sourcegraph/sourcegraph/issues/53177

## Test plan

<img width="622" alt="image"
src="https://github.com/sourcegraph/sourcegraph/assets/23356519/0a1399a4-9364-4891-826d-e3b89a35e822">