dotcom/productsubscription: allow SA to do license key lookup (#54399)
This is required for upcoming Cloud automation:
https://github.com/sourcegraph/controller/pull/805

Currently we can't do the lookup:

```
ERROR mi2.instance.check.enforce.Enforce.cody mi2/instance.go:511 error encountered {"TraceId": "03e4d62c01a89c6a62e5d2e8f1cb6df6", "SpanId": "98bf6654fdf74de6", "environment": "prod", "instance": "src-96ed006bb45d673944e4", "error": "GetEmbeddingsIndexerToken: getSubscription: GetProductSubscriptionByLicense: input: dotcom.productLicenses must be site admin"}
```

## Test plan

unit tests on the `serviceAccountOrSiteAdmin` helper